import { ArrowRight, Search, ShieldCheck, X } from "lucide-react";
import { useMemo, useState } from "react";
import { Link } from "wouter";
import { CatalogueBackToTop } from "../components/CatalogueBackToTop";
import { PageShell } from "../components/PageShell";
import { AddToQuoteButton } from "../components/QuoteCart";
import { getPpeVisualAssets, PPE_CATALOGUE, PPE_CATEGORY_GROUPS, PPE_HERO_VISUAL, PPE_PRODUCT_FAMILIES, PPE_VISUAL_ASSETS } from "../lib/ppeCatalogue";

export default function SafetyPpe() {
  const [query, setQuery] = useState("");
  const groups = useMemo(() => PPE_CATEGORY_GROUPS.map((group) => ({ ...group, families: group.families.filter((family) => `${group.title} ${family.title}`.toLowerCase().includes(query.trim().toLowerCase())) })).filter((group) => group.families.length > 0), [query]);

  return <PageShell>
    <section className="ppe-hero"><div className="ppe-hero-grid" aria-hidden="true" /><div className="content-wrap ppe-hero-layout"><div className="ppe-hero-copy"><span className="eyebrow">Safety equipment • Workwear</span><h1>Protection planned for the work ahead.</h1><p>Explore Bridge Wax Safety &amp; PPE product families for workwear, site protection, emergency readiness, and specialist industrial tasks. Build a clear requirement, then request a considered quotation.</p><div className="button-row"><a href="#ppe-catalogue" className="button button-gold">Explore Safety &amp; PPE <ArrowRight size={16} /></a><Link href="/contact?product=Safety%20%26%20PPE" className="button button-outline-light">Request PPE Support</Link></div><div className="ppe-hero-stats"><span><b>{PPE_CATEGORY_GROUPS.length}</b> Protection areas</span><span><b>{PPE_PRODUCT_FAMILIES.length}</b> Product families</span><span><b>1</b> Quotation team</span></div></div><div className="ppe-hero-media"><img src={PPE_HERO_VISUAL.image} alt={PPE_HERO_VISUAL.alt} loading="eager" decoding="async" /></div></div></section>
    <section className="section section-white ppe-intro"><div className="content-wrap"><nav className="catalogue-breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/products">Products</Link><span>/</span><strong>Safety &amp; PPE</strong></nav><div className="section-heading ppe-heading"><span className="eyebrow">Structured for safer work</span><h2>Discover by protection requirement.</h2><p>Start with the protection area, refine by the product family, then share task, hazard, quantity, and workplace conditions with the Bridge Wax team. Product-family listings are quotation categories; manufacturers, specifications, and availability are confirmed before supply.</p></div><div className="ppe-assurance-grid"><article><ShieldCheck aria-hidden="true" /><div><h3>Quotation-led selection</h3><p>Match PPE requirements to the work environment, task exposure, and your internal safety standard.</p></div></article><article><ShieldCheck aria-hidden="true" /><div><h3>Category-led discovery</h3><p>Use a practical PPE taxonomy before narrowing down approved manufacturer and sizing options.</p></div></article><article><ShieldCheck aria-hidden="true" /><div><h3>Industrial-ready support</h3><p>Coordinate workwear and safety equipment requests with broader mining, laboratory, and site needs.</p></div></article></div></div></section>
    <section className="section section-white ppe-visual-showcase"><div className="content-wrap"><div className="catalogue-section-intro"><div><span className="eyebrow">Visual catalogue</span><h2>Selected Safety &amp; PPE product families.</h2><p>Representative approved imagery for enquiry-led workwear and high-visibility categories.</p></div><Link href="#ppe-catalogue" className="catalogue-product-view">Explore all protection areas <ArrowRight size={15} /></Link></div><div className="ppe-visual-grid">{PPE_VISUAL_ASSETS.map((asset) => { const groupTitle = PPE_CATEGORY_GROUPS.find((group) => group.slug === asset.groupSlug)?.title ?? "Safety & PPE"; return <article className="ppe-visual-card" key={asset.id}><div className="ppe-visual-image"><img src={asset.image} alt={asset.alt} loading="lazy" decoding="async" onError={(event) => { event.currentTarget.style.display = "none"; event.currentTarget.parentElement?.classList.add("image-failed"); }} /></div><div><span>{groupTitle}</span><h3>{asset.title}</h3><AddToQuoteButton product={{ code: `PPE-VISUAL-${asset.id.toUpperCase()}`, name: asset.title, categorySlug: "safety-ppe", categoryTitle: "Safety & PPE", rangeTitle: groupTitle }} /></div></article>; })}</div></div></section>
    <section className="section section-muted" id="ppe-catalogue"><div className="content-wrap"><div className="catalogue-discovery-heading"><div><span className="eyebrow">Safety &amp; PPE catalogue</span><h2>Find a protection family.</h2><p>Search within the original Bridge Wax Safety &amp; PPE taxonomy.</p></div><p className="catalogue-result-count" aria-live="polite"><strong>{groups.reduce((total, group) => total + group.families.length, 0)}</strong> of {PPE_PRODUCT_FAMILIES.length} product families shown</p></div><div className="ppe-search"><Search size={19} aria-hidden="true" /><label className="sr-only" htmlFor="ppe-search-input">Search Safety and PPE product families</label><input id="ppe-search-input" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search workwear, gloves, respirators, fall protection…" /><button type="button" hidden={!query} onClick={() => setQuery("")} aria-label="Clear PPE search"><X size={16} /></button></div><div className="ppe-category-grid">{groups.map((group) => { const categoryImage = getPpeVisualAssets(group.slug)[0]; return <article className="ppe-category-card" id={group.slug} key={group.slug}>{categoryImage && <div className="ppe-category-image"><img src={categoryImage.image} alt="" loading="lazy" decoding="async" onError={(event) => { event.currentTarget.style.display = "none"; event.currentTarget.parentElement?.classList.add("image-failed"); }} /></div>}<div className="ppe-category-card-header"><span>Protection area</span><strong>{group.families.length} families</strong></div><h3>{group.title}</h3><p>{group.description}</p><ul>{group.families.map((family) => <li key={family.slug}>{family.title}</li>)}</ul><AddToQuoteButton product={{ code: `PPE-CATEGORY-${group.slug.toUpperCase()}`, name: `${group.title} selection`, categorySlug: "safety-ppe", categoryTitle: "Safety & PPE", rangeTitle: `${group.title} · ${group.families.length} families` }} /></article>; })}</div>{groups.length === 0 && <div className="catalogue-empty-results"><h3>No PPE product families found.</h3><p>Try a broader protection term or request help from the Bridge Wax team.</p><button type="button" className="button button-dark" onClick={() => setQuery("")}>Clear search</button></div>}</div></section>
    <section className="section section-dark"><div className="content-wrap ppe-cta"><div><span className="eyebrow">PPE support</span><h2>Need a coordinated site-safety requirement?</h2><p>Include roles, workplace conditions, expected quantities, sizing requirements, and the protection challenge in your quotation request.</p></div><Link href="/contact?product=Safety%20%26%20PPE" className="button button-gold">Request Safety &amp; PPE Support <ArrowRight size={16} /></Link></div></section>
    <CatalogueBackToTop />
  </PageShell>;
}
